# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7758d202433531822b3d83ad3c2dc75573d981a01404977bbb0b3ad1abdae2b069c7632d466c6e500f532eb05c3a3482ad17d604d15f5fa9f8d771653f72ad53

test:
  secret_key_base: 911f4197b4c3fa1f67a017ecb37d204e6755f753349a5448ccd25f79a0f27d285df454281d498b991bde49e819d394502e40f956011059eeb8ce8e2782e2ae92

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
